spring:
  application:
    name: ms-accounts

  datasource:
    url: jdbc:mysql://localhost:3306/devsu_bank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: superclave
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # dev only; luego validate + Flyway
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081

ms:
  customers:
    base-url: http://localhost:8080
